name: Lint check

on: workflow_dispatch

jobs:
  lint-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - run: dotnet format --verify-no-changes
